// <auto-generated />
using System;
using API_MEI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_MEI.Data.Migrations
{
    [DbContext(typeof(API_MEIContext))]
    [Migration("20230513171536_edicao_aluno-anoletivo_trabalhos")]
    partial class edicao_alunoanoletivo_trabalhos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_MEI.Models.Alunos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Curso")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Edicao")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Instituicao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Numero_Aluno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("API_MEI.Models.Docentes", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Filiacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("API_MEI.Models.Empresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email_empresa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("API_MEI.Models.Especialistas", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Empresa_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Empresa_Id");

                    b.ToTable("Especialistas");
                });

            modelBuilder.Entity("API_MEI.Models.Juri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Data_Defesa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Trabalho_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Trabalho_Id")
                        .IsUnique();

                    b.ToTable("Juri");
                });

            modelBuilder.Entity("API_MEI.Models.JuriMembros", b =>
                {
                    b.Property<int>("Juri_Id")
                        .HasColumnType("int");

                    b.Property<int>("Membro_Id")
                        .HasColumnType("int");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Juri_Id", "Membro_Id");

                    b.HasIndex("Membro_Id");

                    b.ToTable("JuriMembros");
                });

            modelBuilder.Entity("API_MEI.Models.Membros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Contacto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Membros");
                });

            modelBuilder.Entity("API_MEI.Models.Orientadores", b =>
                {
                    b.Property<int>("Trabalho_Id")
                        .HasColumnType("int");

                    b.Property<int>("Membro_Id")
                        .HasColumnType("int");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Trabalho_Id", "Membro_Id");

                    b.HasIndex("Membro_Id");

                    b.ToTable("Orientadores");
                });

            modelBuilder.Entity("API_MEI.Models.Trabalhos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdendaProtocolo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Aluno_Id")
                        .HasColumnType("int");

                    b.Property<int>("Ano_Letivo")
                        .HasColumnType("int");

                    b.Property<int?>("Empresa_Id")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenciaInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Aluno_Id")
                        .IsUnique();

                    b.HasIndex("Empresa_Id");

                    b.ToTable("Trabalhos");
                });

            modelBuilder.Entity("API_MEI.Models.Docentes", b =>
                {
                    b.HasOne("API_MEI.Models.Membros", "Membros")
                        .WithOne("Docentes")
                        .HasForeignKey("API_MEI.Models.Docentes", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("API_MEI.Models.Especialistas", b =>
                {
                    b.HasOne("API_MEI.Models.Empresas", "Empresas")
                        .WithMany("Especialistas")
                        .HasForeignKey("Empresa_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_MEI.Models.Membros", "Membros")
                        .WithOne("Especialistas")
                        .HasForeignKey("API_MEI.Models.Especialistas", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresas");

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("API_MEI.Models.Juri", b =>
                {
                    b.HasOne("API_MEI.Models.Trabalhos", "Trabalho")
                        .WithOne("Juri")
                        .HasForeignKey("API_MEI.Models.Juri", "Trabalho_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("API_MEI.Models.JuriMembros", b =>
                {
                    b.HasOne("API_MEI.Models.Juri", "Juri")
                        .WithMany("JuriMembros")
                        .HasForeignKey("Juri_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_MEI.Models.Membros", "Membros")
                        .WithMany("JuriMembros")
                        .HasForeignKey("Membro_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Juri");

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("API_MEI.Models.Orientadores", b =>
                {
                    b.HasOne("API_MEI.Models.Membros", "Membros")
                        .WithMany("Orientadores")
                        .HasForeignKey("Membro_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_MEI.Models.Trabalhos", "Trabalho")
                        .WithMany("Orientadores")
                        .HasForeignKey("Trabalho_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membros");

                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("API_MEI.Models.Trabalhos", b =>
                {
                    b.HasOne("API_MEI.Models.Alunos", "Alunos")
                        .WithOne("Trabalho")
                        .HasForeignKey("API_MEI.Models.Trabalhos", "Aluno_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_MEI.Models.Empresas", "Empresas")
                        .WithMany("Trabalho")
                        .HasForeignKey("Empresa_Id");

                    b.Navigation("Alunos");

                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("API_MEI.Models.Alunos", b =>
                {
                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("API_MEI.Models.Empresas", b =>
                {
                    b.Navigation("Especialistas");

                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("API_MEI.Models.Juri", b =>
                {
                    b.Navigation("JuriMembros");
                });

            modelBuilder.Entity("API_MEI.Models.Membros", b =>
                {
                    b.Navigation("Docentes");

                    b.Navigation("Especialistas");

                    b.Navigation("JuriMembros");

                    b.Navigation("Orientadores");
                });

            modelBuilder.Entity("API_MEI.Models.Trabalhos", b =>
                {
                    b.Navigation("Juri");

                    b.Navigation("Orientadores");
                });
#pragma warning restore 612, 618
        }
    }
}
