// <auto-generated />
using System;
using API_MEI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_MEI.Data.Migrations
{
    [DbContext(typeof(API_MEIContext))]
    [Migration("20230414013851_createDatabase")]
    partial class createDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_MEI.Models.Alunos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curso")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Numero_Aluno")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("API_MEI.Models.Docentes", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Docente_Id")
                        .HasColumnType("int");

                    b.Property<string>("Filiacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Docente_Id")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("API_MEI.Models.Empresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email_empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("API_MEI.Models.Especialistas", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Empresa_ID")
                        .HasColumnType("int");

                    b.Property<int>("Especialista_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Empresa_ID");

                    b.HasIndex("Especialista_Id")
                        .IsUnique();

                    b.ToTable("Especialistas");
                });

            modelBuilder.Entity("API_MEI.Models.Juri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data_Defesa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Juri");
                });

            modelBuilder.Entity("API_MEI.Models.JuriMembros", b =>
                {
                    b.Property<int>("Juri_Id")
                        .HasColumnType("int");

                    b.Property<int>("Membros_Id")
                        .HasColumnType("int");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Juri_Id", "Membros_Id");

                    b.HasIndex("Membros_Id");

                    b.ToTable("JuriMembros");
                });

            modelBuilder.Entity("API_MEI.Models.Membros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Membros");
                });

            modelBuilder.Entity("API_MEI.Models.Orientadores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Orientadores");
                });

            modelBuilder.Entity("API_MEI.Models.OrientadoresMembros", b =>
                {
                    b.Property<int>("OrientadorId")
                        .HasColumnType("int");

                    b.Property<int>("MembrosId")
                        .HasColumnType("int");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrientadorId", "MembrosId");

                    b.HasIndex("MembrosId");

                    b.ToTable("OrientadoresMembros");
                });

            modelBuilder.Entity("API_MEI.Models.Trabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Aluno_Id")
                        .HasColumnType("int");

                    b.Property<int>("Empresa_Id")
                        .HasColumnType("int");

                    b.Property<int>("Juri_Id")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orientadores_Id")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Aluno_Id")
                        .IsUnique();

                    b.HasIndex("Empresa_Id");

                    b.HasIndex("Juri_Id")
                        .IsUnique();

                    b.HasIndex("Orientadores_Id");

                    b.ToTable("Trabalho");
                });

            modelBuilder.Entity("API_MEI.Models.Docentes", b =>
                {
                    b.HasOne("API_MEI.Models.Membros", "Membros")
                        .WithOne("Docentes")
                        .HasForeignKey("API_MEI.Models.Docentes", "Docente_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("API_MEI.Models.Especialistas", b =>
                {
                    b.HasOne("API_MEI.Models.Empresas", "Empresas")
                        .WithMany("Especialistas")
                        .HasForeignKey("Empresa_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_MEI.Models.Membros", "Membros")
                        .WithOne("Especialistas")
                        .HasForeignKey("API_MEI.Models.Especialistas", "Especialista_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresas");

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("API_MEI.Models.JuriMembros", b =>
                {
                    b.HasOne("API_MEI.Models.Juri", "Juri")
                        .WithMany("JuriMembros")
                        .HasForeignKey("Juri_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_MEI.Models.Membros", "Membros")
                        .WithMany("JuriMembros")
                        .HasForeignKey("Membros_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Juri");

                    b.Navigation("Membros");
                });

            modelBuilder.Entity("API_MEI.Models.OrientadoresMembros", b =>
                {
                    b.HasOne("API_MEI.Models.Membros", "Membros")
                        .WithMany("OrientadoresMembros")
                        .HasForeignKey("MembrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_MEI.Models.Orientadores", "Orientadores")
                        .WithMany("OrientadoresMembros")
                        .HasForeignKey("OrientadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membros");

                    b.Navigation("Orientadores");
                });

            modelBuilder.Entity("API_MEI.Models.Trabalho", b =>
                {
                    b.HasOne("API_MEI.Models.Alunos", "Alunos")
                        .WithOne("Trabalho")
                        .HasForeignKey("API_MEI.Models.Trabalho", "Aluno_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_MEI.Models.Empresas", "Empresas")
                        .WithMany("Trabalho")
                        .HasForeignKey("Empresa_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_MEI.Models.Juri", "Juri")
                        .WithOne("Trabalho")
                        .HasForeignKey("API_MEI.Models.Trabalho", "Juri_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_MEI.Models.Orientadores", "Orientadores")
                        .WithMany("Trabalho")
                        .HasForeignKey("Orientadores_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alunos");

                    b.Navigation("Empresas");

                    b.Navigation("Juri");

                    b.Navigation("Orientadores");
                });

            modelBuilder.Entity("API_MEI.Models.Alunos", b =>
                {
                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("API_MEI.Models.Empresas", b =>
                {
                    b.Navigation("Especialistas");

                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("API_MEI.Models.Juri", b =>
                {
                    b.Navigation("JuriMembros");

                    b.Navigation("Trabalho");
                });

            modelBuilder.Entity("API_MEI.Models.Membros", b =>
                {
                    b.Navigation("Docentes");

                    b.Navigation("Especialistas");

                    b.Navigation("JuriMembros");

                    b.Navigation("OrientadoresMembros");
                });

            modelBuilder.Entity("API_MEI.Models.Orientadores", b =>
                {
                    b.Navigation("OrientadoresMembros");

                    b.Navigation("Trabalho");
                });
#pragma warning restore 612, 618
        }
    }
}
